# Generated by Django 4.0.4 on 2024-03-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='timeslots',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
