# Generated by Django 4.0.4 on 2024-03-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faculty_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
