# Generated by Django 4.0.4 on 2024-03-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_facultykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
