# Generated by Django 4.0.4 on 2024-03-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCourse',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField(unique=True)),
                ('access_code', models.TextField(default='', max_length=1000)),
                ('time', models.TextField(default='', max_length=1000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onecourses', to='main.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.faculty')),
            ],
            options={
                'verbose_name_plural': 'OneCourses',
                'unique_together': {('code', 'department', 'name')},
            },
        ),
    ]
