# Generated by Django 4.0.4 on 2024-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bookedclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedclasses',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
