# Generated by Django 4.0.4 on 2024-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
