# Generated by Django 4.0.4 on 2024-03-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
