# Generated by Django 4.0.4 on 2024-03-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_course_studentkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedclasses',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='main.course'),
        ),
        migrations.AddField(
            model_name='onecourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onecourses', to='main.course'),
        ),
    ]
