# Generated by Django 4.0.4 on 2024-03-10 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bookedclasses_course_onecourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faccode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='faculty',
            name='facis_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='factoken',
            field=models.UUIDField(default=uuid.UUID('53cfb67b-31e8-44b2-a4a1-ad69722efdc1')),
        ),
        migrations.AddField(
            model_name='student',
            name='stucode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='stuis_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='stutoken',
            field=models.UUIDField(default=uuid.UUID('67a939fe-6903-433e-8edf-81ba019b7462')),
        ),
    ]
